# Generated by Django 4.0.10 on 2023-05-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='customer_name',
        ),
    ]
