# Generated by Django 4.0.10 on 2023-05-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_rename_name_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='watch_name', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='newPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='oldPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
