# Generated by Django 4.0.10 on 2023-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_order_description_order_name_order_newprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='watch_name', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('oldPrice', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('newPrice', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
