# Generated by Django 4.0.10 on 2023-05-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oldPrice',
        ),
    ]
