# Generated by Django 4.0.10 on 2023-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_remove_order_description_remove_order_oldprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='newPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='watch.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='hello1', upload_to='pics'),
        ),
    ]
