# Generated by Django 4.0.10 on 2023-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_remove_order_name_remove_order_newprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(to='watch.order'),
        ),
    ]
