# Generated by Django 4.0.10 on 2023-05-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_product_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
    ]
