# Generated by Django 4.0.10 on 2023-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0009_remove_product_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
