# Generated by Django 4.0.10 on 2023-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0010_order_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='top',
        ),
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
