# Generated by Django 4.0.10 on 2023-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_remove_order_top_product_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
