# Generated by Django 4.0.10 on 2023-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0012_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='watch.product'),
        ),
    ]
